# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7zuM8vz5W-mHq4jfk7P1-RKQ3MxxyyF
"""

from google.colab import files
uploaded = files.upload()

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

# Load  the CSV file
df = pd.read_csv("products-1000.csv")

# 1. Total Stock by Category wise
category_stock = df.groupby("Category")["Stock"].sum().sort_values(ascending=False)
category_stock.plot(kind="bar", color="skyblue", figsize=(8,5))
plt.title("Total Stock by Category")
plt.xlabel("Total Stock")
plt.ylabel("Category")
plt.tight_layout(pad=4.0)
plt.show()

# 2. Average Price by Category wise
avg_price = df.groupby("Category")["Price"].mean().sort_values(ascending=False)
avg_price.plot(kind="bar", color="orange", figsize=(8,5))
plt.title("Average Price by Category")
plt.xlabel("Average Price in (USD)")
plt.ylabel("Category")
plt.tight_layout(pad=4.0)
plt.show()

# 3. Availability Status Distribution overall
availability_count = df["Availability"].value_counts()
availability_count.plot(kind="pie", autopct='%1.1f%%', figsize=(5,5), colors=["lightgreen","pink","lightblue","orange"])
plt.title("Availability Status Distribution")
plt.legend(title="Availability", loc="upper right")
plt.ylabel("")
plt.show()